#include "native_recorder_backend_shared.inl"
#include "native_recorder_backend_qsv.inl"
#include "native_recorder_backend_nvenc.inl"
#include "native_recorder_backend_amf.inl"
#include "native_recorder_backend_factory.inl"
